/* Jeopardy review game. Uses the dashboard's local browser storage. */
(() => {
'use strict';
const KEY='bjhJeopardy_v1';
const $=id=>document.getElementById(id), copy=x=>JSON.parse(JSON.stringify(x));
const uid=()=>globalThis.crypto?.randomUUID?.() || Date.now().toString(36)+Math.random().toString(36).slice(2);
const say=text=>{$('notice').textContent=text;};
const make=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
const sample=[
['Story Elements',['Who is the central character in a story?','The protagonist.'],['What do we call the time and place of a story?','The setting.'],['What is the turning point or moment of greatest tension in a plot?','The climax.'],['How does an internal conflict differ from an external conflict?','Internal conflict occurs within a character; external conflict involves an outside force.'],['Explain how a theme differs from a plot summary.','A theme is a message or insight about life; a plot summary tells what happens.']],
['Suspense',['What feeling does suspense create for the audience?','Anxiety, concern, or excitement about what might happen.'],['What technique gives hints about later events?','Foreshadowing.'],['What is dramatic irony?','The audience knows something a character does not.'],['How can slowing down a dangerous moment create suspense?','It delays the outcome and makes the audience anticipate what will happen.'],['A character opens a door, gasps, and the chapter ends. Name the technique and explain its effect.','A cliffhanger: the unresolved moment makes the reader want to discover what happens next.']],
['Figurative Language',['Name the comparison: “Her smile was like sunshine.”','Simile.'],['Name the comparison: “The classroom was a zoo.”','Metaphor.'],['Name the technique: “The wind whispered through the trees.”','Personification.'],['What does “I have told you a million times” illustrate?','Hyperbole: deliberate exaggeration.'],['Explain the effect of “The hallway swallowed his footsteps.”','Personification makes the hallway seem alive and may create an eerie or isolating mood. Accept other supported explanations.']],
['Grammar',['Which is a verb: quietly, jump, or blue?','Jump.'],['Choose the correct word: “They left (their / there / they’re) books.”','Their.'],['Correct this sentence: “She don’t like rain.”','She doesn’t like rain.'],['Combine these independent clauses correctly: “It was late. We kept reading.”','For example: “It was late, but we kept reading.” Accept another grammatically correct combination.'],['Why is “Because the bell rang” a fragment?','It is a dependent clause and needs an independent clause to complete the thought.']],
['Reading & Evidence',['What is a narrator?','The voice that tells a story.'],['What is an inference?','A conclusion drawn from evidence and reasoning.'],['What is the difference between a quotation and a paraphrase?','A quotation repeats exact words; a paraphrase restates the meaning in new words.'],['What should follow a piece of evidence in an analytical paragraph?','Explanation connecting the evidence to the claim.'],['A character says “I’m fine” while shaking and avoiding eye contact. Make an inference and support it.','The character may be nervous or upset; shaking and avoiding eye contact support that inference. Accept another evidence-based interpretation.']]
];
function starter(){return {id:uid(),title:'ELA Review — Starter Board',categories:sample.map(([name,...qs])=>({name,questions:qs.map(([question,answer])=>({question,answer}))}))};}
function validBoard(b){return b && typeof b.title==='string' && b.title.trim() && b.title.length<=100 && Array.isArray(b.categories) && b.categories.length===5 && b.categories.every(c=>typeof c.name==='string' && c.name.trim() && c.name.length<=80 && Array.isArray(c.questions) && c.questions.length===5 && c.questions.every(q=>typeof q.question==='string' && typeof q.answer==='string' && q.question.length<=4000 && q.answer.length<=4000 && !!q.question.trim()===!!q.answer.trim())) && b.categories.some(c=>c.questions.some(q=>q.question.trim()));}
let data={boards:[starter()],game:null,competition:null}, broken=false;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!Array.isArray(parsed.boards)||!parsed.boards.length||!parsed.boards.every(validBoard))throw Error('Invalid saved boards');data=parsed;}}
catch(e){broken=true;say('Saved game data could not be read. Existing data has been preserved. Restore a browser backup before continuing.');}
if(!Object.prototype.hasOwnProperty.call(data,'competition'))data.competition=null;
function persist(){if(broken)throw Error('Saved data could not be read; no changes were saved.');localStorage.setItem(KEY,JSON.stringify(data));}
function action(fn){return async(...args)=>{try{await fn(...args);}catch(e){const message=e.message||'The action could not be completed.';say(message);if(document.querySelector('dialog[open]'))alert(message);}};}
function on(id,fn){$(id).onclick=action(fn);}
function classes(){return window.DashboardData?.getClasses({activeOnly:true})||[];}
function options(el,items){el.replaceChildren(...items.map(([value,text])=>{const o=make('option',text);o.value=value;return o;}));}
function boardList(id){options($('boards'),data.boards.map(b=>[b.id,b.title]));if(id)$('boards').value=id;}
function periods(){const before=$('period').value;options($('period'),classes().map(c=>[String(c.id),c.name]));$('period').value=classes().some(c=>String(c.id)===before)?before:String(DashboardData.getCurrentClassId());if(!$('period').value)$('period').selectedIndex=0;}
function selected(){return data.boards.find(b=>b.id===$('boards').value);}
function valueAt(index){return (index%5+1)*100;}
function questionAt(g,index){return g.board.categories[Math.floor(index/5)].questions[index%5];}
function total(g){return g.board.categories.reduce((sum,c)=>sum+c.questions.reduce((s,q,r)=>s+(q.question.trim()?(r+1)*100:0),0),0);}
function gameScore(g){return Math.max(0,g.teams.reduce((sum,t)=>sum+Number(t.score||0),0));}
function renderDayCompetition(){const c=data.competition,section=$('dayCompetition');section.hidden=!c||!!data.game;if(!c)return;if(!data.game&&!c.awarded){$('scoreboardMode').value='day';if(data.boards.some(b=>b.id===c.boardId))$('boards').value=c.boardId;}const rows=Object.values(c.results||{}).sort((a,b)=>Number(a.period)-Number(b.period));$('dayCompetitionInfo').textContent=`${c.boardTitle} · ${rows.length} class result${rows.length===1?'':'s'} saved${c.awarded?` · Awarded to ${c.season}`:''}.`;$('dayResults').replaceChildren(...rows.map(row=>{const tr=make('tr');tr.append(make('td',row.name),make('td',String(row.score)));return tr;}));$('awardDay').disabled=!rows.length||!!c.awarded;$('clearDay').textContent=c.awarded?'Start new competition':'Clear competition';}
function render(){const g=data.game;$('setup').hidden=!!g;$('play').hidden=!g;renderDayCompetition();if(!g)return;
$('gameTitle').textContent=g.board.title;$('gameInfo').textContent=`${g.periodName} · ${g.done.length} of ${g.board.categories.flatMap(c=>c.questions).filter(q=>q.question.trim()).length} questions played${g.awarded?' · Points awarded':''}${g.scoreboardMode==='day'?' · Class-day competition':''}`;
$('scores').replaceChildren(...g.teams.map(t=>{const el=make('div',t.name,'score');el.append(make('strong',String(t.score)));return el;}));
const board=$('board');board.replaceChildren(...g.board.categories.map(c=>make('div',c.name,'category')));
for(let r=0;r<5;r++)for(let c=0;c<5;c++){const i=c*5+r,q=questionAt(g,i),done=g.done.includes(i);const btn=make('button',!q.question.trim()?'—':done?'✓':String(valueAt(i)),'tile');btn.disabled=done||!q.question.trim()||!!g.awarded;btn.setAttribute('aria-label',`${g.board.categories[c].name}, ${valueAt(i)} points${done?', completed':''}`);btn.onclick=action(()=>openClue(i));board.append(btn);}
$('undo').disabled=!g.history.length||!!g.awarded;$('award').disabled=!!g.awarded;$('award').textContent=g.scoreboardMode==='day'?'Finish class game':'Finish & award points';$('end').textContent=g.awarded?'New game':'Close game';}
let editId=null;
function edit(board){editId=board?.id||null;const b=board||{title:'',categories:Array.from({length:5},(_,i)=>({name:`Category ${i+1}`,questions:Array.from({length:5},()=>({question:'',answer:''}))}))};$('title').value=b.title;$('fields').replaceChildren();b.categories.forEach((c,ci)=>{const field=make('fieldset');field.append(make('legend',`Category ${ci+1}`));const label=make('label','Category name');const input=make('input');input.id=`cat${ci}`;input.value=c.name;input.required=true;input.maxLength=80;label.append(input);field.append(label);c.questions.forEach((q,ri)=>{const row=make('div',undefined,'edit-question');row.append(make('strong',String((ri+1)*100)));['question','answer'].forEach(key=>{const l=make('label',key==='question'?'Question':'Answer');const t=make('textarea');t.id=`${key}${ci}${ri}`;t.value=q[key];t.rows=2;t.maxLength=4000;l.append(t);row.append(l);});field.append(row);});$('fields').append(field);});$('editor').showModal();}
on('new',()=>edit());on('edit',()=>edit(selected()));on('cancelEdit',()=>$('editor').close());
$('editorForm').onsubmit=action(e=>{e.preventDefault();const b={id:editId||uid(),title:$('title').value.trim(),categories:Array.from({length:5},(_,ci)=>({name:$(`cat${ci}`).value.trim(),questions:Array.from({length:5},(_,ri)=>({question:$(`question${ci}${ri}`).value.trim(),answer:$(`answer${ci}${ri}`).value.trim()}))}))};if(!validBoard(b)){alert('Add a title, five category names, and at least one complete question and answer. Each filled question needs an answer.');return;}const i=data.boards.findIndex(x=>x.id===editId);if(i<0)data.boards.push(b);else data.boards[i]=b;persist();boardList(b.id);$('editor').close();say('Board saved.');});
$('mode').onchange=()=>{$('teamLabel').hidden=$('mode').value!=='teams';};
on('start',()=>{if(broken)throw Error('Saved data must be restored before starting.');const b=selected(),period=classes().find(c=>String(c.id)===$('period').value),scoreboardMode=$('scoreboardMode').value==='day'?'day':'single';if(!period)throw Error('Choose a visible class period in Dashboard Settings.');let names=$('mode').value==='teams'?$('names').value.split('\n').map(s=>s.trim()).filter(Boolean):[period.name];if(names.length<1||names.length>10||names.some(n=>n.length>60))throw Error('Enter 1–10 team names, each 60 characters or fewer.');if(new Set(names).size!==names.length)throw Error('Give each team a different name.');if(scoreboardMode==='day'){if(data.competition?.awarded)data.competition=null;if(data.competition&&data.competition.boardId!==b.id)throw Error('A class-day competition is already using a different board. Award or clear those results first.');if(data.competition?.results?.[String(period.id)]&&!confirm(period.name+' already has a saved result in this competition. Replay it and replace that score?'))return;if(!data.competition)data.competition={id:uid(),boardId:b.id,boardTitle:b.title,createdAt:Date.now(),results:{},awarded:false};}data.game={id:uid(),board:copy(b),period:String(period.id),periodName:period.name,teams:names.map(name=>({name,score:0})),deduct:$('deduct').checked,done:[],history:[],pending:null,awarded:false,scoreboardMode};persist();DashboardData.setCurrentClass(String(period.id));say('');render();});
function openClue(i){const g=data.game;if(g.awarded)return;if(g.pending&&g.pending.index!==i)throw Error('Finish the question already in progress first.');if(!g.pending){g.pending={index:i,before:g.teams.map(t=>t.score),attempted:[],revealed:false};persist();}const p=g.pending,q=questionAt(g,i);$('clueLabel').textContent=`${g.board.categories[Math.floor(i/5)].name} · ${valueAt(i)} points`;$('question').textContent=q.question;$('answer').textContent=q.answer;options($('respondent'),g.teams.map((t,i)=>[String(i),t.name]));clueState();$('clue').showModal();}
function clueState(){const g=data.game,p=g.pending;$('answer').hidden=!p.revealed;$('reveal').hidden=p.revealed;const unavailable=p.attempted.includes(Number($('respondent').value));$('correct').disabled=unavailable;$('incorrect').disabled=unavailable;$('attemptInfo').textContent=p.attempted.length?'Teams that answered incorrectly cannot answer again. Choose another team or skip.':'';}
$('respondent').onchange=clueState;
on('reveal',()=>{data.game.pending.revealed=true;persist();clueState();});
on('back',()=>{$('clue').close();});
function finish(){const g=data.game,p=g.pending;g.history.push({index:p.index,scores:p.before});g.done.push(p.index);g.pending=null;persist();$('clue').close();render();}
on('correct',()=>{const g=data.game,p=g.pending,i=Number($('respondent').value);if(p.attempted.includes(i))return;g.teams[i].score+=valueAt(p.index);finish();});
on('incorrect',()=>{const g=data.game,p=g.pending,i=Number($('respondent').value);if(p.attempted.includes(i))return;p.attempted.push(i);if(g.deduct)g.teams[i].score-=valueAt(p.index);if(p.attempted.length===g.teams.length)finish();else{persist();const next=g.teams.findIndex((_,i)=>!p.attempted.includes(i));$('respondent').value=String(next);clueState();render();}});
on('skip',finish);
on('undo',()=>{const g=data.game;if(g.pending)throw Error('Finish or skip the question in progress before using Undo.');const h=g.history.pop();if(!h)return;g.teams.forEach((t,i)=>t.score=h.scores[i]);g.done=g.done.filter(i=>i!==h.index);persist();render();});
on('end',()=>{if(!data.game.awarded&&!confirm('Close this game without saving or awarding its result? The current game progress will be cleared. Your review board stays saved.'))return;data.game=null;persist();periods();render();say('Ready for the next game.');});
on('award',()=>{const g=data.game;if(g.pending)throw Error('Finish or skip the current question first.');if(!g.done.length)throw Error('Play at least one question before finishing the game.');if(!classes().some(c=>String(c.id)===g.period))throw Error('This class is hidden. Enable it in Dashboard Settings before awarding points.');const earned=gameScore(g);if(g.scoreboardMode==='day'){const comp=data.competition;if(!comp||comp.boardId!==g.board.id)throw Error('The class-day competition could not be found.');comp.results[g.period]={period:g.period,name:g.periodName,score:earned,gameId:g.id};data.game=null;persist();periods();render();say(`${g.periodName} saved with ${earned} game points. Play the next class or award the competition when ready.`);return;}GameCompetitionAward.open({eventId:`jeopardy-${g.id}`,name:`Jeopardy: ${g.board.title}`,scores:[{period:g.period,name:g.periodName,score:earned}],sourceApp:'Jeopardy',sourceId:g.id,onAward:result=>{g.awarded=true;persist();render();say(result.added?'Jeopardy result added to the scoreboard.':'This game was already on the scoreboard; no duplicate points were added.');}});});
on('awardDay',()=>{const c=data.competition;if(!c||c.awarded)throw Error('There is no open class-day competition to award.');const scores=Object.values(c.results||{});if(!scores.length)throw Error('Play at least one class game first.');GameCompetitionAward.open({eventId:`jeopardy-day-${c.id}`,name:`Jeopardy: ${c.boardTitle}`,scores,sourceApp:'Jeopardy',sourceId:c.id,onAward:result=>{c.awarded=true;c.season=result.season;c.eventId=result.event.id;c.awardedAt=Date.now();persist();render();say(result.added?'Class-day Jeopardy results added to the scoreboard.':'These competition results were already on the scoreboard; no duplicate points were added.');}});});
on('clearDay',()=>{const c=data.competition;if(!c)return;if(!c.awarded&&!confirm('Clear the saved class-day Jeopardy results? This cannot be undone.'))return;data.competition=null;persist();render();say(c.awarded?'Ready for a new class-day competition.':'Class-day competition cleared.');});
on('present',async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await document.body.requestFullscreen();});document.addEventListener('fullscreenchange',()=>{$('present').textContent=document.fullscreenElement?'Exit full screen':'Full screen';});
on('export',()=>{const b=selected(),url=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));const a=make('a');a.href=url;a.download=(b.title.replace(/[^a-z0-9-]+/gi,'-')||'Jeopardy')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
on('import',()=>$('file').click());$('file').onchange=action(async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>1000000)throw Error('Choose a board JSON file smaller than 1 MB.');const b=JSON.parse(await f.text());if(!validBoard(b))throw Error('This file is not a valid five-category Jeopardy board.');b.id=uid();data.boards.push(b);persist();boardList(b.id);say('Board imported.');}finally{$('file').value='';}});
window.addEventListener('storage',e=>{if(e.key===KEY){say('Jeopardy changed in another tab. Reload this page to continue with the latest game.');document.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=true);broken=true;}});
window.addEventListener(DashboardData.changeEvent,()=>{periods();renderDayCompetition();});
boardList();periods();try{if(data.game&&(!validBoard(data.game.board)||!Array.isArray(data.game.teams)||!Array.isArray(data.game.done)||!Array.isArray(data.game.history)))throw Error('Invalid saved game.');render();if(data.game?.pending)openClue(data.game.pending.index);}catch(e){broken=true;say('Saved game progress could not be read. Existing data has been preserved.');}
})();
